// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceObjects.Data;

#nullable disable

namespace SpaceObjects.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622083934_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceObjects.Entities.CosmoObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("AgeInBillionYears")
                        .HasColumnType("double precision");

                    b.Property<double>("MassInTons")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("SpeedKmPerSecond")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.ToTable("CosmoObjects");

                    b.HasDiscriminator<string>("Type").HasValue("CosmoObject");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SpaceObjects.Entities.Asteroid", b =>
                {
                    b.HasBaseType("SpaceObjects.Entities.CosmoObject");

                    b.Property<double>("DiameterInKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Asteroid");
                });

            modelBuilder.Entity("SpaceObjects.Entities.BlackHole", b =>
                {
                    b.HasBaseType("SpaceObjects.Entities.CosmoObject");

                    b.Property<double>("EventHorizonRadiusInKm")
                        .HasColumnType("double precision");

                    b.Property<double>("GravityPower")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("BlackHole");
                });

            modelBuilder.Entity("SpaceObjects.Entities.Planet", b =>
                {
                    b.HasBaseType("SpaceObjects.Entities.CosmoObject");

                    b.Property<string>("Atmosphere")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasLife")
                        .HasColumnType("boolean");

                    b.Property<double>("RadiusInKm")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("Planet");
                });

            modelBuilder.Entity("SpaceObjects.Entities.Star", b =>
                {
                    b.HasBaseType("SpaceObjects.Entities.CosmoObject");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TemperatureInKelvin")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("Star");
                });
#pragma warning restore 612, 618
        }
    }
}
